file_format: "1"
id: kyria_rev3_d
name: Kyria Rev3 dongle
type: shield
url: https://splitkb.com/products/kyria-pcb-kit
requires: [pro_micro]
exposes: [i2c_oled]
features:
  - keys
  - display
  - encoder
  - underglow
siblings:
  - kyria_rev3_d_dongle
  - kyria_rev3_d_left
  - kyria_rev3_d_right
