file_format: "1"
id: kyria_rev3_d
name: Kyria Rev3 (PS/2 trackpoint)
type: shield
url: https://splitkb.com/products/kyria-pcb-kit
requires: [pro_micro]
features:
  - keys
  - encoder
siblings:
  - kyria_rev3_d_left
  - kyria_rev3_d_right
