# LL connection-timing renegotiation (BT 4.1 CPR) collided with macOS sleep
CONFIG_BT_CTLR_CONN_PARAM_REQ=n

# Trackpoint requires interrupt-driven uart driver, instead of the default async
CONFIG_UART_INTERRUPT_DRIVEN=y
