# Disable battery reporting
CONFIG_BT_BAS=n

CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# split
CONFIG_BT=y
CONFIG_ZMK_SPLIT=y
CONFIG_ZMK_SPLIT_ROLE_CENTRAL=y

CONFIG_ZMK_MOUSE=y

CONFIG_ZMK_EXT_POWER=n
CONFIG_ZMK_RGB_UNDERGLOW=n
