manifest:
  remotes:
    - name: badjeff
      url-base: https://github.com/badjeff
  projects:
    - name: zmk
      remote: badjeff
      revision: 773dec58eaacaef4703b3e4595e50bd71f6cad3d
      import: app/west.yml
    - name: kb_zmk_ps2_mouse_trackpoint_driver
      remote: badjeff
      revision: 7ab7846a95b233c3ada0e0605b972f36353e7bc4
  self:
    path: config
